# Updated : 2025.07.07
# Version : 1.1.3
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_2.yaml
  bms_errors_bitmask: !include bms_errors_bitmask_JK_RS485_Modbus.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

jk_rs485_bms:
  - id: jk_rs485_bms${bms_id}
    rs485_address: ${bms_address}
    jk_rs485_sniffer_id: ${sniffer_id}
    update_interval: ${bms_update_interval}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    charging:
      id: bms${bms_id}_charge_switch
      name: "${name} ${bms_name} charging"
    discharging:
      id: bms${bms_id}_discharge_switch
      name: "${name} ${bms_name} discharging"
    balancing:
      id: bms${bms_id}_balance_switch
      name: "${name} ${bms_name} balancing"
    emergency:
      name: "${name} ${bms_name} emergency"
    heating:
      name: "${name} ${bms_name} heating"
    display_always_on:
      name: "${name} ${bms_name} display_always_on"
    disable_temperature_sensors:
      name: "${name} ${bms_name} disable temperature sensors"
    smart_sleep_on:
      name: "${name} ${bms_name} smart sleep on"

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    status_balancing:
      id: bms${bms_id}_equalizing
      name: "${name} ${bms_name} status balancing"
    status_charging:
      id: bms${bms_id}_charging_allowed
      name: "${name} ${bms_name} status charging"
    status_discharging:
      id: bms${bms_id}_discharging_allowed
      name: "${name} ${bms_name} status discharging"
    status_online:
      id: bms${bms_id}_online_status
      name: "${name} ${bms_name} status online"
    status_heating:
      name: "${name} ${bms_name} status heating"

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    balancing_direction:
      name: "${name} ${bms_name} balancing direction"
    cell_voltage_min:
      id: bms${bms_id}_min_cell_voltage
      name: "${name} ${bms_name} cell voltage min"
    cell_voltage_max:
      id: bms${bms_id}_max_cell_voltage
      name: "${name} ${bms_name} cell voltage max"
    cell_voltage_min_cell_number:
      id: bms${bms_id}_min_voltage_cell
      name: "${name} ${bms_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      id: bms${bms_id}_max_voltage_cell
      name: "${name} ${bms_name} cell voltage max cell number"
    cell_delta_voltage:
      name: "${name} ${bms_name} cell delta voltage"
    cell_average_voltage:
      id: bms${bms_id}_average_cell_voltage
      name: "${name} ${bms_name} cell average voltage"
    cell_resistance_min:
      name: "${name} ${bms_name} cell resistance min"
    cell_resistance_max:
      name: "${name} ${bms_name} cell resistance max"
    cell_resistance_min_cell_number:
      name: "${name} ${bms_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      name: "${name} ${bms_name} cell resistance max cell number"
    battery_voltage:
      id: bms${bms_id}_total_voltage
      name: "${name} ${bms_name} battery voltage"
    battery_current:
      id: bms${bms_id}_current
      name: "${name} ${bms_name} battery current"
    battery_power:
      id: bms${bms_id}_power
      name: "${name} ${bms_name} battery power"
    battery_power_charging:
      id: bms${bms_id}_charging_power
      name: "${name} ${bms_name} battery power charging"
    battery_power_discharging:
      id: bms${bms_id}_discharging_power
      name: "${name} ${bms_name} battery power discharging"
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      name: "${name} ${bms_name} temperature sensor 1"
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      name: "${name} ${bms_name} temperature sensor 2"
    temperature_sensor_3:
      id: bms${bms_id}_temperature_sensor_3
      name: "${name} ${bms_name} temperature sensor 3"
    temperature_powertube:
      name: "${name} ${bms_name} temperature powertube"
    battery_capacity_state_of_charge:
      id: bms${bms_id}_state_of_charge
      name: "${name} ${bms_name} battery capacity state of charge"
    battery_capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      name: "${name} ${bms_name} battery capacity remaining"
    charging_cycles:
      id: bms${bms_id}_charging_cycles_raw
      internal: true
      name: "${name} ${bms_name} charging cycles"
    battery_capacity_total_charging_cycle:
      id: bms${bms_id}_cycle_capacity_raw
      internal: true
      name: "${name} ${bms_name} battery capacity total charging cycle"
    battery_total_runtime:
      name: "${name} ${bms_name} battery total runtime"
    balancing_current:
      name: "${name} ${bms_name} balancing current"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      name: "${name} ${bms_name} errors bitmask"
    cell_count_real:
      name: "${name} ${bms_name} cell count real"
    battery_total_alarms_count:
      name: "${name} ${bms_name} battery total alarms count"
    battery_total_alarms_active:
      name: "${name} ${bms_name} battery total alarms active"
    uart1_protocol_number:
      name: "${name} ${bms_name} uart1 protocol number"
    battery_soh_valuation:
      id: bms${bms_id}_battery_soh
      name: "${name} ${bms_name} battery soh valuation"
    cell_voltage_01:
      name: "${name} ${bms_name} cell voltage 01"
    cell_voltage_02:
      name: "${name} ${bms_name} cell voltage 02"
    cell_voltage_03:
      name: "${name} ${bms_name} cell voltage 03"
    cell_voltage_04:
      name: "${name} ${bms_name} cell voltage 04"
    cell_voltage_05:
      name: "${name} ${bms_name} cell voltage 05"
    cell_voltage_06:
      name: "${name} ${bms_name} cell voltage 06"
    cell_voltage_07:
      name: "${name} ${bms_name} cell voltage 07"
    cell_voltage_08:
      name: "${name} ${bms_name} cell voltage 08"
    cell_voltage_09:
      name: "${name} ${bms_name} cell voltage 09"
    cell_voltage_10:
      name: "${name} ${bms_name} cell voltage 10"
    cell_voltage_11:
      name: "${name} ${bms_name} cell voltage 11"
    cell_voltage_12:
      name: "${name} ${bms_name} cell voltage 12"
    cell_voltage_13:
      name: "${name} ${bms_name} cell voltage 13"
    cell_voltage_14:
      name: "${name} ${bms_name} cell voltage 14"
    cell_voltage_15:
      name: "${name} ${bms_name} cell voltage 15"
    cell_voltage_16:
      name: "${name} ${bms_name} cell voltage 16"
    # cell_voltage_17:
    #   name: "${name} ${bms_name} cell voltage 17"
    # cell_voltage_18:
    #   name: "${name} ${bms_name} cell voltage 18"
    # cell_voltage_19:
    #   name: "${name} ${bms_name} cell voltage 19"
    # cell_voltage_20:
    #   name: "${name} ${bms_name} cell voltage 20"
    # cell_voltage_21:
    #   name: "${name} ${bms_name} cell voltage 21"
    # cell_voltage_22:
    #   name: "${name} ${bms_name} cell voltage 22"
    # cell_voltage_23:
    #   name: "${name} ${bms_name} cell voltage 23"
    # cell_voltage_24:
    #   name: "${name} ${bms_name} cell voltage 24"
    cell_resistance_01:
      name: "${name} ${bms_name} cell resistance 01"
    cell_resistance_02:
      name: "${name} ${bms_name} cell resistance 02"
    cell_resistance_03:
      name: "${name} ${bms_name} cell resistance 03"
    cell_resistance_04:
      name: "${name} ${bms_name} cell resistance 04"
    cell_resistance_05:
      name: "${name} ${bms_name} cell resistance 05"
    cell_resistance_06:
      name: "${name} ${bms_name} cell resistance 06"
    cell_resistance_07:
      name: "${name} ${bms_name} cell resistance 07"
    cell_resistance_08:
      name: "${name} ${bms_name} cell resistance 08"
    cell_resistance_09:
      name: "${name} ${bms_name} cell resistance 09"
    cell_resistance_10:
      name: "${name} ${bms_name} cell resistance 10"
    cell_resistance_11:
      name: "${name} ${bms_name} cell resistance 11"
    cell_resistance_12:
      name: "${name} ${bms_name} cell resistance 12"
    cell_resistance_13:
      name: "${name} ${bms_name} cell resistance 13"
    cell_resistance_14:
      name: "${name} ${bms_name} cell resistance 14"
    cell_resistance_15:
      name: "${name} ${bms_name} cell resistance 15"
    cell_resistance_16:
      name: "${name} ${bms_name} cell resistance 16"
    # cell_resistance_17:
    #   name: "${name} ${bms_name} cell resistance 17"
    # cell_resistance_18:
    #   name: "${name} ${bms_name} cell resistance 18"
    # cell_resistance_19:
    #   name: "${name} ${bms_name} cell resistance 19"
    # cell_resistance_20:
    #   name: "${name} ${bms_name} cell resistance 20"
    # cell_resistance_21:
    #   name: "${name} ${bms_name} cell resistance 21"
    # cell_resistance_22:
    #   name: "${name} ${bms_name} cell resistance 22"
    # cell_resistance_23:
    #   name: "${name} ${bms_name} cell resistance 23"
    # cell_resistance_24:
    #   name: "${name} ${bms_name} cell resistance 24"

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    errors:
      name: "${name} ${bms_name} errors"
    total_runtime_formatted:
      name: "${name} ${bms_name} total runtime formatted"
    info_vendorid:
      name: "${name} ${bms_name} info vendorid"
    info_hardware_version:
      name: "${name} ${bms_name} info hardware version"
    info_software_version:
      name: "${name} ${bms_name} info software version"
    info_device_name:
      name: "${name} ${bms_name} info device name"
    info_device_password:
      name: "${name} ${bms_name} info device password"
    network_nodes_available:
      name: "${name} ${bms_name} network nodes available"
    info_device_serial_number:
      name: "${name} ${bms_name} info device serial number"
    info_device_setup_passcode:
      name: "${name} ${bms_name} info device setup passcode"

number:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    cell_smart_sleep_voltage:
      name: "${name} ${bms_name} cell smart sleep voltage"
    battery_capacity_total_settings:
      id: bms${bms_id}_battery_capacity
      name: "${name} ${bms_name} battery capacity total setting"
    cell_count_settings:
      id: bms${bms_id}_cell_count
      name: "${name} ${bms_name} cell count settings"
    max_charging_current:
      id: bms${bms_id}_max_charge_current
      name: "${name} ${bms_name} max charging current"
    max_discharging_current:
      id: bms${bms_id}_max_discharge_current
      name: "${name} ${bms_name} max discharging current"
    cell_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      name: "${name} ${bms_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      id: bms${bms_id}_cell_ovpr
      name: "${name} ${bms_name} cell overvoltage protection recovery"
    cell_balancing_trigger_voltage:
      id: bms${bms_id}_balance_trigger_voltage
      name: "${name} ${bms_name} balancing trigger voltage"
    cell_balancing_starting_voltage:
      name: "${name} ${bms_name} cell balancing starting voltage"
    max_balancing_current:
      name: "${name} ${bms_name} max balancing current"
    cell_soc100_voltage:
      name: "${name} ${bms_name} cell soc100 voltage"
    cell_soc0_voltage:
      name: "${name} ${bms_name} cell soc0 voltage"
    cell_undervoltage_protection:
      id: bms${bms_id}_cell_uvp
      name: "${name} ${bms_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      id: bms${bms_id}_cell_uvpr
      name: "${name} ${bms_name} cell undervoltage protection recovery"
    cell_power_off_voltage:
      name: "${name} ${bms_name} cell power off voltage"
