# Updated : 2025.06.12
# Version : 1.1.5
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# https://github.com/Xinyuan-LilyGO/T-CAN485

substitutions:
  board_chip: "ESP32"
  board_name: "LilyGo T-CAN485"
  # Interfaces GPIOs
  # GPIO 34-39 does not support output pin mode.
  # uart_esp_1 (RS485 port)
  tx_pin_1: '22'
  rx_pin_1: '21'
  # uart_esp_2
  tx_pin_2: '32'
  rx_pin_2: '34'
  # uart_esp_3
  tx_pin_3: '33'
  rx_pin_3: '35'
  # canbus_esp32_can (CAN port)
  tx_pin_4: '27'
  rx_pin_4: '26'
  # canbus_mcp2515
  spi_mosi_pin: '12'
  spi_miso_pin: '5'
  spi_clk_pin: '18'
  mcp2515_cs_pin: '25'

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  board_rgb_led: !include board_options_rgb_led_status.yaml

esp32:
  board: esp32dev
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"

# +--------------------------------------+
# | Inverter Heartbeat Light             |
# +--------------------------------------+

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: esp32_rmt_led_strip
    id: esp_light
    rgb_order: GRB
    pin: 4
    num_leds: 1
    # rmt_channel: 0
    chipset: ws2812
    entity_category: config
    default_transition_length: 0ms

# +--------------------------------------+
# | LilyGo T-CAN485 related config       |
# +--------------------------------------+

output:
  # MAX13487E SHDN (enable RS485 chip)
  - platform: gpio
    id: RS485_SE
    pin:
      number: 19
      inverted: true # set HIGH level
  # MAX13487E RE (enable RS485 autodirection)
  - platform: gpio
    id: RS485_EN
    pin:
      number: 17
      inverted: true # set HIGH level
  # RS485 and CAN Boost power supply
  - platform: gpio
    id: CGQ_EN
    pin:
      number: 16
      inverted: true # set HIGH level
  # SN65HVD231DR RS PIN (CAN high speed mode)
  - platform: gpio
    id: CAN_SE
    pin:
      number: 23
      inverted: false # set LOW level
