# Updated : 2025.08.12
# Version : 1.1.4
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# https://github.com/OLIMEX/ESP32-EVB

substitutions:
  board_chip: "ESP32"
  board_name: "EVB"
  # Interfaces GPIOs
  # uart_esp_1
  tx_pin_1: '4'
  rx_pin_1: '36'
  # uart_esp_2
  tx_pin_2: '16'
  rx_pin_2: '13'
  # canbus_esp32_can
  tx_pin_4: '5'
  rx_pin_4: '35'

packages:
  device_base: !include ../base/device_base.yaml
  device_base_ethernet: !include ../base/device_base_ethernet.yaml

esp32:
  board: esp32-evb
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

ethernet:
  id: my_network
  type: LAN8720
  mdc_pin: 23
  mdio_pin: 18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 0

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"

# +--------------------------------------+
# | Inverter Heartbeat Light             |
# +--------------------------------------+

light:
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: binary
    id: esp_light
    output: esp_output

output:
  # ESP32 board without LED
  - platform: template
    id: esp_output
    type: binary
    write_action:
      - logger.log: "Inverter Heartbeat Output"
      #- lambda: C++ code; # action to be performed at each inverter heartbeat
