# Updated : 2025.08.11
# Version : 1.1.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  canbus: !include yambms_canbus.yaml

select:
  # YamBMS - Inverter Communication Protocol
  - id: !extend ${canbus_id}_bms_name
    web_server:
      sorting_group_id: yambms_inverter_communication_protocol
  - id: !extend ${canbus_id}_protocol
    web_server:
      sorting_group_id: yambms_inverter_communication_protocol

binary_sensor:
  # YamBMS - Inverter Communication Protocol
  - id: !extend ${canbus_id}_status
    web_server:
      sorting_group_id: yambms_inverter_communication_protocol
